site_name: Go API Docs
theme:
  name: material
site_url: https://github.com/Alan-Gomes1/go-api

theme:
  name: material
  language: pt-BR
  palette:
    # Paleta para modo claro
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Mudar para o modo escuro
    # Paleta para modo escuro
    - scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Mudar para o modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo:
  favicon:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alan-gomes1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seu-usuario/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
